version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - ./src/main/resources/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306