server:
  port: 8080
  servlet:
    context-path: /todolist
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
